version: '3.4'

services:
  speedweb:
    image: speedweb
    restart: unless-stopped
    build:
      context: .
      dockerfile: src/services/WebApplication/Dockerfile
    ports:
      - 5090:5090
  clientapp:
    image: clientapp
    restart: unless-stopped
    build:
      context: src/clientapp
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  proxy:
    image: nginx:latest
    tty: true
    hostname: proxy
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
networks:
  app-network:
    driver: bridge
